import type { ProfileUser, ProfileQuiz, Transaction, Referral, FavoriteQuiz, SavedPaymentMethod } from "./profile-types";

export const profileUser: ProfileUser = {
  name: "John Adam",
  title: "Human Resource Manager",
  location: "Toronto, Canada",
  avatar: "/user1.png",
  referralLink: "https://technitest.com/ref/john-adam-83ka",
  coins: 250,
  issuedCoins: 100,
  issuedDate: "Jan 15, 2026",
  expiryDate: "Jan 15, 2027",
};

export const profileQuizzes: ProfileQuiz[] = [
  {
    id: "q1",
    title: "Advanced Marketing Quiz BBA",
    category: "Business & Management",
    description: "Test your knowledge of advanced marketing principles, strategies, and best practices.",
    level: "Advanced",
    score: 35,
    maxScore: 40,
    percentage: 87,
    totalQuestions: 40,
    duration: "45 min",
    lastAttemptDate: "Jul 10, 2026",
    attemptNumber: 2,
    totalAttempts: 3,
    status: "passed",
    image: "/trendingQuiz/quiz1.png",
    reportUrl: "#",
    certificateUrl: "#",
  },
  {
    id: "q2",
    title: "Digital Marketing Fundamentals",
    category: "Marketing",
    description: "Cover essential digital marketing concepts including SEO, social media, and analytics.",
    level: "Intermediate",
    score: 28,
    maxScore: 40,
    percentage: 70,
    totalQuestions: 40,
    duration: "30 min",
    lastAttemptDate: "Jul 5, 2026",
    attemptNumber: 1,
    totalAttempts: 1,
    status: "passed",
    image: "/trendingQuiz/quiz1.png",
    reportUrl: "#",
    certificateUrl: "#",
  },
  {
    id: "q3",
    title: "Project Management Basics",
    category: "Management",
    description: "Learn the fundamentals of project management, timelines, and resource allocation.",
    level: "Beginner",
    score: 18,
    maxScore: 40,
    percentage: 45,
    totalQuestions: 40,
    duration: "25 min",
    lastAttemptDate: "Jun 28, 2026",
    attemptNumber: 1,
    totalAttempts: 2,
    status: "failed",
    image: "/trendingQuiz/quiz1.png",
  },
  {
    id: "q4",
    title: "Financial Accounting Essentials",
    category: "Finance",
    description: "Understand core accounting principles, balance sheets, and financial statements.",
    level: "Intermediate",
    score: 32,
    maxScore: 40,
    percentage: 80,
    totalQuestions: 40,
    duration: "40 min",
    lastAttemptDate: "Jun 20, 2026",
    attemptNumber: 3,
    totalAttempts: 3,
    status: "passed",
    image: "/trendingQuiz/quiz1.png",
    reportUrl: "#",
    certificateUrl: "#",
  },
];

export const profileTransactions: Transaction[] = [
  {
    id: "t1",
    orderId: "754890",
    type: "quiz",
    status: "success",
    refundStatus: "non-refundable",
    date: "Aug 18, 2024 / 12:53:20",
    amount: 540.0,
    currency: "USD",
    paymentMethod: "Credit Card",
    receiptUrl: "#",
    invoiceUrl: "#",
  },
  {
    id: "t2",
    orderId: "754891",
    type: "re-attempt",
    status: "success",
    refundStatus: "refundable",
    date: "Sep 02, 2024 / 09:15:44",
    amount: 120.0,
    currency: "USD",
    paymentMethod: "Credit Card",
    receiptUrl: "#",
    invoiceUrl: "#",
  },
  {
    id: "t3",
    orderId: "754892",
    type: "renewal",
    status: "cancelled",
    refundStatus: "non-refundable",
    date: "Oct 14, 2024 / 16:30:11",
    amount: 89.0,
    currency: "USD",
    paymentMethod: "PayPal",
    receiptUrl: "#",
    invoiceUrl: "#",
  },
  {
    id: "t4",
    orderId: "754893",
    type: "quiz",
    status: "success",
    refundStatus: "non-refundable",
    date: "Nov 05, 2024 / 11:05:33",
    amount: 200.0,
    currency: "USD",
    paymentMethod: "Credit Card",
    receiptUrl: "#",
    invoiceUrl: "#",
  },
];

export const profileReferrals: Referral[] = [
  {
    id: "r1",
    name: "Talha Iqbal",
    email: "talha@example.com",
    phone: "000-000-000",
    coinsEarned: 25,
    registeredOn: "Mar 23, 2023",
    status: "active",
    statusDate: "Aug 18, 2024",
  },
  {
    id: "r2",
    name: "Sara Khan",
    email: "sara.k@example.com",
    phone: "000-111-222",
    coinsEarned: 25,
    registeredOn: "Jun 10, 2023",
    status: "active",
    statusDate: "Sep 05, 2024",
  },
  {
    id: "r3",
    name: "Ahmed Raza",
    email: "ahmed.r@example.com",
    phone: "000-333-444",
    coinsEarned: 25,
    registeredOn: "Jan 15, 2024",
    status: "expired",
    statusDate: "Jul 15, 2024",
  },
  {
    id: "r4",
    name: "Maria Lee",
    email: "maria.l@example.com",
    phone: "000-555-666",
    coinsEarned: 25,
    registeredOn: "Apr 08, 2024",
    status: "active",
    statusDate: "Oct 08, 2024",
  },
  {
    id: "r5",
    name: "Bilal Shah",
    email: "bilal.s@example.com",
    phone: "000-777-888",
    coinsEarned: 25,
    registeredOn: "Feb 20, 2024",
    status: "expired",
    statusDate: "Aug 20, 2024",
  },
];

export const profileFavoriteQuizzes: FavoriteQuiz[] = [
  {
    id: "fq1",
    title: "Advanced Marketing Quiz BBA",
    category: "Business & Management",
    description: "Test your knowledge of advanced marketing principles, strategies, and best practices.",
    level: "Advanced",
    rating: 4.5,
    duration: "45 min",
    totalQuestions: 40,
    image: "/trendingQuiz/quiz1.png",
    resultUrl: "/quiz/advanced-marketing/result",
    isFavorite: true,
  },
  {
    id: "fq2",
    title: "Digital Marketing Fundamentals",
    category: "Marketing",
    description: "Cover essential digital marketing concepts including SEO, social media, and analytics.",
    level: "Intermediate",
    rating: 4.2,
    duration: "30 min",
    totalQuestions: 40,
    image: "/trendingQuiz/quiz1.png",
    resultUrl: "/quiz/digital-marketing/result",
    isFavorite: true,
  },
  {
    id: "fq3",
    title: "Financial Accounting Essentials",
    category: "Finance",
    description: "Understand core accounting principles, balance sheets, and financial statements.",
    level: "Intermediate",
    rating: 4.7,
    duration: "40 min",
    totalQuestions: 40,
    image: "/trendingQuiz/quiz1.png",
    resultUrl: "/quiz/financial-accounting/result",
    isFavorite: true,
  },
  {
    id: "fq4",
    title: "HR Management Basics",
    category: "Human Resources",
    description: "Learn the fundamentals of HR management, recruitment, and employee relations.",
    level: "Beginner",
    rating: 4.0,
    duration: "25 min",
    totalQuestions: 30,
    image: "/trendingQuiz/quiz1.png",
    resultUrl: "/quiz/hr-management/result",
    isFavorite: true,
  },
];

export const profileSavedPayments: SavedPaymentMethod[] = [
  {
    id: "sp1",
    provider: "stripe",
    holderName: "John Adam",
    maskedNumber: "**** **** **** 4242",
    date: "Jul 10, 2026",
    isDefault: true,
  },
  {
    id: "sp2",
    provider: "paypal",
    holderName: "John Adam",
    maskedNumber: "john@adam.com",
    date: "Jun 22, 2026",
    isDefault: false,
  },
  {
    id: "sp3",
    provider: "jazzcash",
    holderName: "John Adam",
    maskedNumber: "**** *** 1234",
    date: "May 15, 2026",
    isDefault: false,
  },
];
